services:
  nestapp:
    container_name: nestapp
    image: hendisantika/nestapp:1.0.0
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=mysql
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_DB=nestapp
      - PG_PORT=3306
      - PG_HOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestapp
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data: { }
